### ISSUE TITLE
Ramsey Uuid version 4

### ISSUE THREAD

**Issue by clarkeash** [Innmind/ScalewaySdk#1]
Hi, I was wondering if you would be willing to upgrade to `ramsey/uuid` version 4 to allow use of this library in Laravel 8 and beyond?

**Comment by Baptouuuu** [comment]
I'll try to take a look at it this week end

**Comment by Baptouuuu** [comment]
The version `2.2.0` has been released allowing `ramsey/uuid` `^4.0`.

Note that not all `ramsey/uuid` versions support php 8.1. For now this package is not tested against php 8.1, to do so it would require the minimum version of `ramsey/uuid` to be higher.
